# Generated by Django 4.2.6 on 2023-10-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idProduct', models.IntegerField(primary_key=True, serialize=False)),
                ('cProductName', models.CharField(max_length=100, verbose_name='Material')),
                ('cDescription', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('xType', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('xU', models.CharField(blank=True, max_length=100, null=True, verbose_name='xU')),
                ('xAreaCapacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='g/m2')),
                ('xCapacity', models.FloatField(blank=True, null=True, verbose_name='gm')),
                ('xDensity', models.FloatField(blank=True, null=True, verbose_name='Densidade')),
                ('nValue', models.FloatField(blank=True, null=True, verbose_name='Valor Unit')),
            ],
        ),
        migrations.CreateModel(
            name='SalesMan',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idSalesMan', models.IntegerField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100, verbose_name='Vendedor')),
                ('cPhone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cEmail', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('dCreated', models.DateTimeField(auto_now_add=True)),
                ('dLastUpdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idTax', models.IntegerField(primary_key=True, serialize=False)),
                ('cTaxDescription', models.CharField(max_length=300, verbose_name='Descrição')),
                ('cAcronym', models.CharField(max_length=20, verbose_name='Sigla')),
                ('xType', models.CharField(max_length=10, verbose_name='Tipo')),
                ('nValue', models.FloatField(verbose_name='Valor')),
                ('nValueCalculated', models.FloatField(verbose_name='Valor Imposto')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idCustomer', models.IntegerField(primary_key=True, serialize=False, verbose_name='idCliente')),
                ('xCustomerDocument', models.CharField(max_length=21, verbose_name='CNPJ')),
                ('cCustomerName', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cCustomerShortName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cPhone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cEmail', models.EmailField(max_length=100, null=True, verbose_name='E-mail')),
                ('xCustomerType', models.CharField(max_length=50, verbose_name='Tipo')),
                ('xCustomerClass', models.CharField(max_length=50, verbose_name='Classe')),
                ('xCustomerStatus', models.CharField(max_length=50, verbose_name='Status')),
                ('xPaymentCondition', models.CharField(max_length=50, verbose_name='Cond. Pag.')),
                ('xListPrice', models.CharField(max_length=100, verbose_name='Lista Preço')),
                ('cObservation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dCreated', models.DateTimeField(auto_now_add=True)),
                ('dLastUpdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('idSalesMan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furukawa.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idContract', models.IntegerField(primary_key=True, serialize=False)),
                ('cVendedor', models.CharField(max_length=100, verbose_name='Vendedor')),
                ('cDescription', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('dContractCreated', models.DateField(null=True, verbose_name='Contrato desde')),
                ('nContractDuration', models.IntegerField(null=True, verbose_name='Tempo de Contrato')),
                ('dLastUpdate', models.DateTimeField(null=True)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furukawa.customer')),
                ('idSalesMan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furukawa.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idContact', models.IntegerField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100, verbose_name='Nome Contato')),
                ('cPhone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cEmail', models.EmailField(max_length=100, verbose_name='Email')),
                ('dCreated', models.DateTimeField(auto_now_add=True)),
                ('dLastUpdate', models.DateTimeField(null=True)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furukawa.customer', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('lActive', models.IntegerField(auto_created=True, default=1)),
                ('idBudget', models.IntegerField(primary_key=True, serialize=False)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='furukawa.product')),
            ],
        ),
    ]
